### ISSUE TITLE
Unable to publish to MQTT broker on HASS_DISCOVERY mode

### ISSUE THREAD

**Issue by bjerem** [vingerha/gazpar_2_mqtt#10]
**Which type of installation/run**
- Container lancé avec docker-compose

**Your configuration**
```
version: '3.5'
services:
  gazpar2mqtt:
    container_name: gazpar2mqtt
    image: vingerha/gazpar_2_mqtt:latest
    tty: true
    restart: unless-stopped
    environment:
      # mandatory:
      - GRDF_USERNAME=MYEMAIL
      - GRDF_PASSWORD=MYPASSWORD
      - MQTT_HOST=192.168.X.X
      - TZ=Europe/Paris
      - STANDALONE_MODE=True
      - DEBUG=True
      - SCHEDULE_TIME=07:30
      - MQTT_PORT=1883
      - MQTT_TOPIC=gazpar2mqtt
      - MQTT_CLIENTID=gazpar2mqtt
      - MQTT_USERNAME=gazpar2mqtt
      - MQTT_PASSWORD=gazpar2mqtt
      - MQTT_QOS=0
      - MQTT_RETAIN=True
      - MQTT_SSL=False
      - HASS_DISCOVERY=True
      - HASS_PREFIX=homeassistant
      - HASS_DEVICE_NAME=gazpar2mqtt
    volumes:
      - ./:/data
      - ./app:/app
    networks:
       lan:
          ipv4_address: 192.168.X.X
networks:
    lan:
      external:
        name: lan
```

**Describe the bug**

J'essaie d'utiliser la fonction HASS_DISCOVERY comme je peux actuellement le faire avec mon container MyElectricalData.
L'export des données fonctionne correctement en mode standalone et j'ai bien le TOPIC gazpar2mqtt dans mon broker. **Cependant, impossible d'exporter les valeurs pour le discovery HomeAssistant (topic homeassistant) vers mon broker MQTT**.
Voici quelques lignes de debug de mon docker-compose logs :

> gazpar2mqtt    | 2024-08-28 21:47:05,471 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO #               Welcome to gazpar2mqtt                    #
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Program version : 0.8.7
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Database version : 0.4.0
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Influxdb version : 0.1.0
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Please note that the the tool is under development, various functions may disappear or be modified.
> gazpar2mqtt    | 2024-08-28 21:47:05,472 DEBUG If you can read this line, you are in DEBUG mode.
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO #                Program parameters                       #
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:05,472 DEBUG GRDF config : username = MYEMAIL, password = MYPASSWORD
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO MQTT broker config : host = 192.168.X.X, port = 1883, clientId = gazpar2mqtt, qos = 0, topic = gazpar2mqtt, retain = True, ssl = False
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Standlone mode : Enable = True
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Home Assistant discovery : Enable = True, Topic prefix = homeassistant, Device name = gazpar2mqtt
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Threshold options : Warning percentage = 80
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Database options : Force reinitialization = False, Path = /data
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Debug mode : Enable = True
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Check parameters...
> gazpar2mqtt    | 2024-08-28 21:47:05,472 INFO Parameters are ok !
> gazpar2mqtt    | 2024-08-28 21:47:05,473 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:05,473 INFO #        Connection to SQLite database                     #
> gazpar2mqtt    | 2024-08-28 21:47:05,473 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:05,473 INFO Connection to SQLite database...
> gazpar2mqtt    | 2024-08-28 21:47:05,473 DEBUG Connexion to database
> gazpar2mqtt    | 2024-08-28 21:47:05,473 INFO SQLite database connected !
> gazpar2mqtt    | 2024-08-28 21:47:05,473 INFO Last execution date 2024-08-28 20:57:03.251315, program was in version 0.8.7.
> gazpar2mqtt    | 2024-08-28 21:47:05,473 INFO Checking database version...
> gazpar2mqtt    | 2024-08-28 21:47:05,473 INFO Your database is already up to date : version 0.4.0.
> gazpar2mqtt    | 2024-08-28 21:47:05,473 INFO Retrieve database statistics...
> gazpar2mqtt    | 2024-08-28 21:47:05,474 INFO 324 informatives measures stored
> gazpar2mqtt    | 2024-08-28 21:47:05,474 INFO 1 PCE(s)
> gazpar2mqtt    | 2024-08-28 21:47:05,474 INFO First measure : 2023-07-20
> gazpar2mqtt    | 2024-08-28 21:47:05,474 INFO Last measure : 2024-08-26
> gazpar2mqtt    | 2024-08-28 21:47:05,474 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:05,474 INFO #              Connection to Mqtt broker                   #
> gazpar2mqtt    | 2024-08-28 21:47:05,474 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:05,474 INFO Connect to Mqtt broker...
> gazpar2mqtt    | 2024-08-28 21:47:05,474 DEBUG Mqtt connect : activation of callbacks
> gazpar2mqtt    | 2024-08-28 21:47:05,474 DEBUG Mqtt connect : connection to broker 192.168.X.X:1883...
> gazpar2mqtt    | 2024-08-28 21:47:05,475 DEBUG Wait for conexion callback
> gazpar2mqtt    | 2024-08-28 21:47:07,475 DEBUG Mqtt on_connect callback : Connection Accepted.
> gazpar2mqtt    | 2024-08-28 21:47:07,476 DEBUG Mqtt on_connect callback : connected
> gazpar2mqtt    | 2024-08-28 21:47:09,475 INFO Mqtt broker connected !
> gazpar2mqtt    | 2024-08-28 21:47:09,476 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:09,476 INFO #            Get data from GRDF website                   #
> gazpar2mqtt    | 2024-08-28 21:47:09,476 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:09,476 DEBUG Connection to GRDF, try 1/14...
> [...]
> gazpar2mqtt    | 2024-08-28 21:47:12,503 DEBUG Retrieve conversion factor between '2024-08-28','start of month','-1 month' and '2024-08-28','start of month','-1 day'
> gazpar2mqtt    | 2024-08-28 21:47:12,504 DEBUG M1 factor : 11 kwh / m3
> gazpar2mqtt    | 2024-08-28 21:47:12,504 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:12,504 INFO #           Stand alone publication mode                  #
> gazpar2mqtt    | 2024-08-28 21:47:12,504 INFO -----------------------------------------------------------
> [...]
> gazpar2mqtt    | 2024-08-28 21:47:12,504 INFO You can retrieve published values subscribing topic gazpar2mqtt/XXXXX/#
> gazpar2mqtt    | 2024-08-28 21:47:12,504 INFO Publishing to Mqtt...
> gazpar2mqtt    | 2024-08-28 21:47:12,505 DEBUG Creation of last informative measures
> gazpar2mqtt    | 2024-08-28 21:47:12,505 DEBUG Mqtt publish : publication...
> [..]
> gazpar2mqtt    | 2024-08-28 21:47:19,924 DEBUG Publishing payload ON to topic gazpar2mqtt/XXXXX/status/connectivity, qos 0, retain True
> gazpar2mqtt    | 2024-08-28 21:47:19,925 DEBUG Mqtt on_publish callback : message published
> gazpar2mqtt    | 2024-08-28 21:47:20,125 INFO Status values published !
> gazpar2mqtt    | 2024-08-28 21:47:20,125 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:20,125 INFO #           Home assistant publication mode               #
> gazpar2mqtt    | 2024-08-28 21:47:20,125 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:20,125 INFO Publishing values of PCE XXXXX alias None...
> gazpar2mqtt    | 2024-08-28 21:47:20,125 INFO ---------------------------------
> **gazpar2mqtt    | 2024-08-28 21:47:20,126 ERROR Home Assistant discovery mode : unable to publish value to mqtt broker**
> gazpar2mqtt    | 2024-08-28 21:47:20,126 INFO -----------------------------------------------------------
> gazpar2mqtt    | 2024-08-28 21:47:20,126 INFO #                    Load prices                          #
> gazpar2mqtt    | 2024-08-28 21:47:20,126 INFO -----------------------------------------------------------

Je reproduis le problème dès que le script tourne.
Le problème est que j'ai pas trop d'info or mis un ERROR pour m'aider au debug.
Merci d'avance pour ton aide.

**Comment by vingerha** [comment]
Jamais vu ça et je ne peux tester car à l'''ertanger. Seul truc .. pourquoi t'as mis MQTT_RETAIN=True ... car défaut est 'false' Je n'ais jamais testé son comportement.

**Comment by vingerha** [comment]
Je ne peux pas reproduire l'erreur, c'est pas mqttt_retain mais je pense que c'est ton 'alias' qui n'est pas défini aupres du site GRDF. 
![image](https://github.com/user-attachments/assets/14525c90-b8d4-4219-9bfd-e3dd8a1afd38)

**Comment by vingerha** [comment]
Si c'est ça je peux éviter pour des autres mais je te demand la preuve. Je ne peux pas effacer la mienne

**Comment by bjerem** [comment]
Effectivement, bien vu !
Je n'avais pas d'alias de noté sur mon compte.
En le renseignant, les messages vers le broker MQTT sous le topic homeassistant ont pu être publiés.

**Avant :** 
![IMG_20240829_205951](https://github.com/user-attachments/assets/4a897394-ad68-4ec5-95b4-13eac5f46cc1)

**Après :** 
![IMG_20240829_210029](https://github.com/user-attachments/assets/947dae26-de9d-463b-8ddd-5593eb68eb70)

```
gazpar2mqtt    | 2024-08-29 20:55:11,190 DEBUG Mqtt on_publish callback : message published
gazpar2mqtt    | 2024-08-29 20:55:11,390 DEBUG Mqtt publish : publication...
gazpar2mqtt    | 2024-08-29 20:55:11,391 DEBUG Publishing payload ON to topic homeassistant/binary_sensor/gazpar2mqtt_XXXXX/connectivity/state, qos 0, retain True
gazpar2mqtt    | 2024-08-29 20:55:11,391 DEBUG Mqtt on_publish callback : message published
gazpar2mqtt    | 2024-08-29 20:55:11,591 INFO Devices published !
```

Le changement du Token MQTT_RETAIN n'a rien donné.
Merci pour ton debug.
