### ISSUE TITLE
[FEATURE]: Reduire la taille du nom sensor

### ISSUE THREAD

**Issue by Sylv01H** [vingerha/gazpar_2_mqtt#7]
**Describe the solution you'd like**
Pouvoir remplacer dans le nom des capteurs le N° de PCE par un alias configurable dans le config.yaml, afin de réduire la longueur des noms de ces capteurs.

**Comment by vingerha** [comment]
Un peu de context comment le nom des sensors est construit
Example: sensor.gazpar_dev_thuis_current_month_of_last_year_gas
- "gazpar_dev" est défjà deinié par une paramètre "HASS_DEVICE_NAME", default: gazpar
- "thuis" est définié par grdf, l'intégration reduit des majuscules et espaces vides 
![image](https://github.com/vingerha/gazpar_2_mqtt/assets/44190435/188f6e93-7ffb-4530-9662-71bb175d6dde)
- current_month_of_last_year_gas est définié par l'intégation et je ne le change pas :)

**Comment by Sylv01H** [comment]
Salut désolé je n'avais pas vu ton post...
Oui je vais faire l'essai...
