### ISSUE TITLE
error HAOS addon

### ISSUE THREAD

**Issue by Amapem** [vingerha/gazpar_2_mqtt#8]
**Which type of installation/run**
- addon

**Your configuration**
not yet

**Describe the bug**
error during addon install : The command '/bin/sh -c apt-get update && apt-get install -y jq' returned a non-zero code: 100

Steps/data to reproduce the behavior, e.g.
install add on

**Additional**

**Comment by vingerha** [comment]
First time that I received an error on an add-on install. Only thought I have is that 'jq' might not be available, can you please retry?
And on what architecture are you installing?

**Comment by vingerha** [comment]
I know at least one user with proxmox. Can you let me know on what hardware the VM runs?

**Comment by titof2375** [comment]
> J'ai déjà essayé plusieurs fois
> 
> Je suis sur une VM promox exécutant HAOS.

Salut tu a installé comment ta VM et a tu les caractéristiques de ta VM ?
